//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlieta.Pdms.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EmailId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public string VerificationDocument { get; set; }
        public string VerificationNumber { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<System.DateTime> HiredDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> InactiveFrom { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
