//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlieta.Pdms.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisit
    {
        public int VisitId { get; set; }
        public int PatientId { get; set; }
        public string ComplaintHistory { get; set; }
        public string ExaminationNotes { get; set; }
        public string Diagnosis { get; set; }
        public string OtherAdvise { get; set; }
        public bool IsFolowUpRequired { get; set; }
        public System.DateTime FollowUpDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
