//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlieta.Pdms.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientImagingData
    {
        public int UniqueId { get; set; }
        public int VisitId { get; set; }
        public int ImagingId { get; set; }
        public string ImagingName { get; set; }
        public string Findings { get; set; }
        public System.DateTime TestDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
