//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlieta.Pdms.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int UniqueId { get; set; }
        public int VisitId { get; set; }
        public int DrugId { get; set; }
        public int DosageFrequencyId { get; set; }
        public string Duration { get; set; }
        public string Units { get; set; }
        public string Instructions { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string DrugName { get; set; }
        public string Dosage { get; set; }
    }
}
