//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlieta.Pdms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentId { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string Name { get; set; }
        public string PatientId { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
