//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlieta.Pdms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int BillingId { get; set; }
        public string BillingNumber { get; set; }
        public System.DateTime BillingDate { get; set; }
        public int Debit { get; set; }
        public int Credit { get; set; }
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public string DoctorName { get; set; }
        public string HospitalName { get; set; }
        public string ServiceName { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string Notes { get; set; }
    }
}
