//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlieta.Pdms
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayBook
    {
        public int DayBookId { get; set; }
        public string BillingNumber { get; set; }
        public System.DateTime BillingDate { get; set; }
        public int Debit { get; set; }
        public int Credit { get; set; }
        public string Notes { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
