//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlieta.Pdms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public int HospitalId { get; set; }
        public string HospitalName { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
