//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlieta.Pdms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surgery
    {
        public int SurgeryId { get; set; }
        public int PatientId { get; set; }
        public Nullable<System.DateTime> SurgeryDate { get; set; }
        public Nullable<int> OperationId { get; set; }
        public Nullable<int> HospitalId { get; set; }
        public string IPNumber { get; set; }
        public string Notes { get; set; }
        public string PreOpDiagnosis { get; set; }
        public string PostOpDiagnosis { get; set; }
        public string ReferredBy { get; set; }
        public Nullable<int> SurgeonId { get; set; }
        public Nullable<int> AssistantSurgeonId { get; set; }
        public Nullable<int> AnaesthetistId { get; set; }
        public Nullable<int> ScrubNurseId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
